services:
  frontend:
    build: ./Frontend
    ports:
      - "80:80"
    environment:
      - PUBLIC_API_URL=${FE_PUBLIC_API_URL}
    develop:
      watch:
        - path: ./Frontend
          action: sync+restart
          target: /app
          ignore:
            - ./Frontend/node_modules
        - path: ./Frontend/bun.lock
          action: rebuild
          target: /app

  api:
    build: ./WebServer
    ports:
      - "8080:80"
    environment:
      - PHOTO_DIR=${BE_PHOTO_DIR}
      - USER_AGENT=${BE_USER_AGENT}
      - DATABASE_URL=${BE_DATABASE_URL}
    volumes:
      - type: bind
        source: ${BE_PHOTO_SRC}
        target: ${BE_PHOTO_DIR}
        read_only: true
    depends_on:
      # db:
      #   condition: service_healthy # Wait for the database to be healthy
      - db
    develop:
      watch:
        - action: sync+restart
          path: ./WebServer
          target: /app
          # Exclude the project virtual environment
          ignore:
            - .venv/
        # Rebuild the image on changes to the `pyproject.toml`
        - action: rebuild
          path: ./uv.lock

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3306:3306" # Expose MySQL port to host
    volumes:
      - db_data:/var/lib/mysql # Persist database data
    # healthcheck:
    #   test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
    #   timeout: 20s
    #   retries: 10

volumes:
  db_data:
